### ISSUE TITLE
Brainstorm week's of action/resources

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/Open-Action-Kit#5]
@sparcopen/ecl-team brainstorm all the things in comments here. If you aren't sure how to comment speak to Joe.

**Comment by parnopaeus** [comment]
Do we want to maybe talk about different KINDS of activities that can be done in OA week? 
e.g. a big lecture (that we often do here at Pitt), an IR deposit drive, tables, workshops, etc.? With examples?

**Comment by rchampieux** [comment]
@parnopaeus +1 to pushing out info on types of activities, this is also an area for which we can ask for community input.  I think it would be useful to categorizing the types of activities and provide info on  things like the typical upfront work needed, obvious/helpful partners, primary audience/s, potential impacts.  This way, people can browse the ideas based on their resources, environment, and goals.  Essentially, I'm being a total librarian and suggesting some type of schema to describe / discover the activities.  🚀 :woman_singer: 🤓

**Comment by rchampieux** [comment]
* I am thinking it could be helpful and logical to stage the info we'll provide in terms of getting from point **A** to point **Z** for both organizing an OA week event, and building a more impactful/strategic professional profile.  
* On a regular basis we would offer a new suggested action and/or resource collection that facilitates one of the two high level aims.  Not everything would need to be big, but the collective parts would help individuals in our community host a successful event/campaign and develop a personal strategy for their professional advancement.
* This sort of approach would provide a project management like plan and actionable resources for both deliverable areas (which would speak to the time management difficulties of the work we do for openness and our careers!).
* Also, as often as possible we could be pointing people to existing resources rather than creating new ones.
* The model itself could provide professional development opportunities, as we could reach out to experts in our community to take the lead on or contribute to specific topics/points in the calendar.

![](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)

**On the OA week event / campaign building side, a few ideas come to mind**
* Strategies for identifying the framing that will resonate with your campus community and connecting openness with other initiatives/needs on campus (as Emma suggested).
* Inventorying the time and resources you and your team can devote to the event/advocacy campaign.
* Finding partners
* Finding event funding.
* Choosing your event or advocacy model.
   * This is where we could push out something like the encyclopedia of event types Lauren suggested.
* Messaging and outreach.
   * This package of information could include boiler plate templates (contributed by the community) and even graphics or inspiration and remixing.
   * This could also be timed in a way that makes sense for kicking off event promotion and sending personal invites for an October OA week event.
* Assessment strategies and communicating success.

**Some ideas for ECL professional advancement strategies content**
* Writing a good professional bio.
* Re-working your CV to describe your leadership experience.
* Virtual Q&A with current leaders like David Lewis
* Strategies (and data) for tracking and communicating your impact.
* Networking strategies (how to connect with the people and orgs you aim to work with/for)
* Creating a personal professional website with Github pages.

**Comment by emolls** [comment]
@rchampieux and @parnopaeus @nshockey Do you think there is content on openaccessweek.org that would mirror some of this? Maybe would be helpful to know how folks in the community are using the site. 

I **REALLY** like the moving from A-Z idea. One of the hardest things for me is capturing the momentum.

**Comment by nshockey** [comment]
I think "activities" might be a useful term that encapsulates the variety of actions we're talking about. I don't want to lean too heavily on "event." Since events have proven less successful on many campuses, I think it's helpful to urge people to think about other ways to be active during the week. Of course, an event can still certainly be one of the activities we suggest / provide guidance on. Sorry if this is word smithing—just trying to make sure we're framing things effectively.

To @emolls' question about content on openaccessweek.org, there is definitely some useful content on successful OA Week actions (especially in the featured content section on the homepage). Right now, people mainly use the OA Week site to download resources (e.g. banners, button graphics, etc), read blogs posted by the community, post their events, and connect within sub-groups users can create. However, we've been discussing rebuilding the OA Week for a little while now but haven't had the bandwidth. I think a site rebuild is likely outside the scope of this group, but any input on how the site could be built to be more useful would certainly be helpful!

**Comment by JosephMcArthur** [comment]
FYI, I have a shell of a page here: http://www.opencon2017.org/ecl-oaweek. If you have any edits to the page title, intro or autoresponser let me know!

**Comment by camillet** [comment]
To build off @emolls and @rchampieux, I think it could be helpful and possibly within the scope of this group to reorganize some of the existing resources and activities on OA Week's website. Personally, I find it a bit hard to navigate and maybe adding some categories (social media campaigns, events, other activities, countries, regions, etc.) along with maybe a For Librarians: leadership toolkit/activities/ events might be helpful. We wouldn't reinvent the wheel, just make them smoother, easier to use. Does that sound feasible?

**Comment by emolls** [comment]
Agreed! In NO WAY was I suggesting a rebuild of the OAWeek site ;) ... @nshockey. 
Agree, @camillet : strong supporter of keeping clean and smooth. Seems everyone loves building repos these days.

**Comment by nshockey** [comment]
Totally agree with this idea to create a curated list of resources. If you have ideas for a larger redesign of the OA Week website, that feedback would be useful, even though the rebuild is outside of the scope of this group!

**Comment by coateshl** [comment]
So many great ideas already suggested by **@rchampieux @parnopaeus @emolls @camillet**. I think it would be especially helpful to provide guidance, examples, and resources for people who are trying to figure out how to align open with institutional priorities, initiatives, etc. I also love the idea of creating templates for messaging & promotion, which would make it a lot easier for small libraries to participate. One thing I don't see is engaging with the local community, which keeps coming up here around our cultural heritage collections and the dataRescue conversations. It would be great to include a couple of activities related to engaging with the community, including public libraries and state libraries, about collections, open access articles, and OER.

**Comment by parnopaeus** [comment]
+1 @coateshl to engaging with the community. For us here, "community" was usually the (many) other libraries near the University of Pittsburgh, hosting joint events for all of the campuses. We have one example of engaging beyond the academic community - a "Historic Pittsburgh" fair a couple of years ago that showed off our open collection of historical photographs and brought in people from the community (such as the local Heinz History Center and the Jewish community archivists) to have tables showcasing their materials. Would be happy to write up some more about that event if that's helpful (as soon as I remind myself of the details... it was way back in 2014!).

Also, I wonder about engaging with a community of scholars, e.g. a scholarly society or a particular discipline? Could be a great way to get subject specialists involved, making a list of OA journals in the discipline, sharing data repositories, highlighting a preprint server, etc.

**Comment by chealsye** [comment]
+1 @camillet! I love the "For Librarians: leadership toolkit/activities/ events" idea. I agree with @coateshl that it would be incredibly helpful to provide examples - both in aligning open with their uni but also just for the sake of having something to build off of.
