### ISSUE TITLE
Draft Resource Dissemination Calendar / Roadmap

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/Open-Action-Kit#8]

**Comment by rchampieux** [comment]
## Draft schedule of information themes and resources we'll deliver between July 2017 and November 2017.

### July
#### Kick off communication or virtual forum, which introduces OA Week 2017 and the resources we will be providing to librarians to facilitate successful actions.  The communication or forum will address: 

* high level info on this year's theme ("open in order to...")
* the kinds of actions/engagement being promoted, specifically the "Open in Order To..." campaigns and doathons
* the specific help we'll be providing between now and October
* call for feedback regarding help/resources our audience would value.

### August
#### Set of light-weight resources that help our audience identify the particular action/s they want to facilitate and move forward with planning, with an emphasis on partnering with local/institutional communities, aligning plans and messaging with institutional goals and interests, and taking your advocacy to the next level.  Potential products include:

* Curated lists of existing resources.  Leveraging @camillet idea of making existing resources easier to use and navigate.
* Inventorying your current environment, resources
* Talking points
* Live or blogged "show and tell"  of specific types of actions, to inspire different models of local activities.
* Forum or blogged interviews on the subject of community engagement and institutional goals alignment. 

### September
#### Deliver and highlight existing templates for facilitating local messaging, and 2-3 profiles on actions community members are planning.  The latter will highlight the what, why, and how and speak across the spectrum of experience we've discussed.

### October 🎆 🥇 🏁 
#### Tricks & tips for addressing last minutes details; ideas and resources for sharing and connecting a local event with broader/international OA Week network; preparing for assessment and bragging 😸 

### November
#### Resources that address strategies for building on and telling the story of your success via/to various forums and audiences (e.g. institutional peers, administrators, your CV).
